### ISSUE TITLE
Logo Design Offer as Open Source Contribution

### ISSUE THREAD

**Issue by anharismail** [keithrbennett/wifiwand#11]
Hello Sir. I'm a UI/UX and Graphics Designer. I'm happy to see an open source project, So, I want provide a logo for you. Would you mind if I propose a new logo design for your project as my Open Source Contribution?

Thanks before.

**Comment by keithrbennett** [comment]
Hello, Sir. Thank you for your kind and generous offer! I'm not sure how we would use it though. Do you have any ideas? If we embed a link to it in the README, and it's not found due to a broken Internet connection, would it look bad in the rendered README? If not, maybe we could use it for that.

**Comment by anharismail** [comment]
Hello, Sir @keithrbennett . This is my logo proposal for your project.
This logo was inspired by wifi and magic wand. I'm very welcome if you have any comments, opinions, or revisions. Please just tell me.

If you like my logo, you can use it on Readme files and merged it on your project repository, So, I'll provide all file types and sizes you needed.

Hope you like it :)

![wifi-wand ver 1](https://user-images.githubusercontent.com/37614260/43682280-5f80f0bc-989a-11e8-991d-8b152334ff85.png)

**Comment by keithrbennett** [comment]
Wow, it's very nice. I like the one with blue in it. I think I would prefer
a rounded circle. What do you think?

I still need to look into how I would host/use it.

Thanks,
Keith

**Comment by keithrbennett** [comment]
Thank you, Anhar. Yes, I would like to use it. What do you think would be a good place for the logo files, a subdirectory named `logo`? If so, please go ahead and do the pull request; if not, let's discuss.

**Comment by keithrbennett** [comment]
Also, I would like to make sure, is there anything in the logo (for example, the font) that is proprietary?

**Comment by anharismail** [comment]
Thanks for will using my logo. For just information, the professional logo must have the typefont identity called logotype. But dont worry I'll provide the logo or icon only, its called logomark. So you can use in many places as you like.

**Comment by keithrbennett** [comment]
I don't understand. What do you mean by "typefont identity" "logotype"? Do you mean "typeface"?  I understand that "logotype" means the word part of the logo and "logomark" is the image, right? I'm trying to understand if there is anything proprietary in either.

**Comment by anharismail** [comment]
Ah sorry, I read so fast on the first time, so dont read the 'proprietary' point carefully.

Yes you right, typeface, typefont, and logotype is the same. and the font I used is open license font. No proprietary fee either.

**Comment by keithrbennett** [comment]
Logo pull request https://github.com/keithrbennett/wifiwand/pull/19 accepted.
