### ISSUE TITLE
"hotspot_login_required" always false

### ISSUE THREAD

**Issue by Anonymousey** [keithrbennett/wifiwand#26]
I would like to use this tool as part of a little project I am working on. I am still playing around with it but I have noticed a bug or perhaps it is just an issue with my curl installation. 

hotspot_login_required will always return false - even if the hotspot requires a login. I have had a look at the code and I can see wifiwand calls curl to check for a 302 redirect. This works fine when the verbose flag is set on curl but using it without (which your code does) returns nothing.

> x@ba68d4b0 ~ % curl --max-time 3 http://captive.apple.com
> x@ba68d4b0 ~ % wifi-wand i                               
> Error obtaining public IP address info, proceeding with everything else:
> 767: unexpected token at ''
> {
>                   "wifi_on" => true,
>              "internet_on" => true,
>    "hotspot_login_required" => false,
>                 "interface" => "en0",
>                   "network" => ".@ AIS SUPER WiFi",
>                "ip_address" => "172.26.72.154",
>               "mac_address" => "50:ed:3c:53:cb:36",
>               "nameservers" => [
>        [0] "115.178.58.10",
>        [1] "115.178.58.26"
>    ],
>                 "timestamp" => 2024-04-24 13:17:04 +0700
>}

While the idea of checking for a 302 redirect is sound. I do wonder if all hotspots will behave this way. I'm pretty sure I have had hotspots return 200 but still require a login. 

MacOS seems to use some sort of method of checking if a WiFi connection needs a login or not as when you click on the AP a small window will appear letting you input your login details if required. Would be interesting to know how MacOS handles that. I might try to investigate that. 

Anyway, just letting you know about the issue. Since I'm in Thailand just now I'll play around with a few hotspots and see how they interact with apples captive portal.

**Comment by keithrbennett** [comment]
It was almost five years ago, May 2019, when I wrote the code to determine whether or not a hotspot login was required. At the time I was aware that there was a lot of complexity involved in getting this information and that my solution was only partial. I judged that, for my own use at least, it was ok if it failed on the edge cases.

Also, at the time, the text test did work without the need for curl's verbose flag.

Thank you for bringing this up. The environment on which this utility relies changes over time, and with clearer thinking and better information, changing the implementation or even removing the feature may be the better way. I'm open to feedback from you and others about this.

Meanwhile I will test this at various places to see how it behaves. Feel free to leave more feedback here. Any research you can do, and/or code you can provide, will be appreciated.

Also, as a side note, I don't know anything about the folks who use this software, and it's encouraging to hear from you. I just started a discussion at https://github.com/keithrbennett/wifiwand/discussions/27 inviting people to say how they use this software and what they might like to see in the future.

**Comment by keithrbennett** [comment]
Given that there is no realistic expectation that there is a satisfactory solution to all instances of this test, or that I would find it if there were one, I have removed the `hotspot_login_required` informational item in version 2.18.0, and will close this issue.

If anyone wants to try to find a good solution, feel free to reopen this or post a new issue.

Thanks again to @Anonymousey for raising the issue, removing the erroneous behavior improves the quality of this project.
