### ISSUE TITLE
Feature Request:  ban network

### ISSUE THREAD

**Issue by SoldierCoder** [keithrbennett/wifiwand#9]
In many cities despite settings to automatically join preferred networks, monolithic commercial ISP intrusively ask users to sign in to their service, forcing users to explicitly change their wifi setting.  It would nice if we could add a command to automatically reject certain ISPs (Cox, Infinity... etc).

**Comment by keithrbennett** [comment]
Hi Ed! Could you clarify...those ISP's networks are _not_ in the list of preferred networks? If not, then I don't know how we would have the ability to do that. If you can point me to any information explaining how they accomplish this, I could take a look.

**Comment by keithrbennett** [comment]
Ed, this software calls underlying OS command line utilities to do its work, and I don't know how this would be done with those utilities. If you or someone wants to research this, I could assist in writing a script, or possibly including it in this software. I'm closing this issue for now, but feel free to reopen or create a new one.
